# Generated by Django 4.1.5 on 2023-01-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='tite',
            new_name='title',
        ),
    ]
